export const QUOTATION_LIST_REQUEST = 'QUOTATION_LIST_REQUEST';
export const QUOTATION_LIST_SUCCESS = 'QUOTATION_LIST_SUCCESS';
export const QUOTATION_LIST_FAIL = 'QUOTATION_LIST_FAIL';

export const QUOTATION_DETAILS_REQUEST = 'QUOTATION_DETAILS_REQUEST';
export const QUOTATION_DETAILS_SUCCESS = 'QUOTATION_DETAILS_SUCCESS';
export const QUOTATION_DETAILS_FAIL = 'QUOTATION_DETAILS_FAIL';
export const QUOTATION_DETAILS_RESET = 'QUOTATION_DETAILS_RESET';

export const QUOTATION_CREATE_REQUEST = 'QUOTATION_CREATE_REQUEST';
export const QUOTATION_CREATE_SUCCESS = 'QUOTATION_CREATE_SUCCESS';
export const QUOTATION_CREATE_FAIL = 'QUOTATION_CREATE_FAIL';
export const QUOTATION_CREATE_RESET = 'QUOTATION_CREATE_RESET';

export const QUOTATION_UPDATE_REQUEST = 'QUOTATION_UPDATE_REQUEST';
export const QUOTATION_UPDATE_SUCCESS = 'QUOTATION_UPDATE_SUCCESS';
export const QUOTATION_UPDATE_FAIL = 'QUOTATION_UPDATE_FAIL';
export const QUOTATION_UPDATE_RESET = 'QUOTATION_UPDATE_RESET';

export const QUOTATION_DELETE_REQUEST = 'QUOTATION_DELETE_REQUEST';
export const QUOTATION_DELETE_SUCCESS = 'QUOTATION_DELETE_SUCCESS';
export const QUOTATION_DELETE_FAIL = 'QUOTATION_DELETE_FAIL';

export const QUOTATION_STATUS_REQUEST = 'QUOTATION_STATUS_REQUEST';
export const QUOTATION_STATUS_SUCCESS = 'QUOTATION_STATUS_SUCCESS';
export const QUOTATION_STATUS_FAIL = 'QUOTATION_STATUS_FAIL';
export const QUOTATION_STATUS_RESET = 'QUOTATION_STATUS_RESET';

export const QUOTATION_CONVERT_REQUEST = 'QUOTATION_CONVERT_REQUEST';
export const QUOTATION_CONVERT_SUCCESS = 'QUOTATION_CONVERT_SUCCESS';
export const QUOTATION_CONVERT_FAIL = 'QUOTATION_CONVERT_FAIL';
export const QUOTATION_CONVERT_RESET = 'QUOTATION_CONVERT_RESET';

export const QUOTATION_CLONE_REQUEST = 'QUOTATION_CLONE_REQUEST';
export const QUOTATION_CLONE_SUCCESS = 'QUOTATION_CLONE_SUCCESS';
export const QUOTATION_CLONE_FAIL = 'QUOTATION_CLONE_FAIL';
export const QUOTATION_CLONE_RESET = 'QUOTATION_CLONE_RESET';

export const PRODUCT_PICKER_REQUEST = 'PRODUCT_PICKER_REQUEST';
export const PRODUCT_PICKER_SUCCESS = 'PRODUCT_PICKER_SUCCESS';
export const PRODUCT_PICKER_FAIL = 'PRODUCT_PICKER_FAIL';
export const PRODUCT_PICKER_RESET = 'PRODUCT_PICKER_RESET';

export const CASH_BILL_CREATE_REQUEST = 'CASH_BILL_CREATE_REQUEST';
export const CASH_BILL_CREATE_SUCCESS = 'CASH_BILL_CREATE_SUCCESS';
export const CASH_BILL_CREATE_FAIL = 'CASH_BILL_CREATE_FAIL';
export const CASH_BILL_CREATE_RESET = 'CASH_BILL_CREATE_RESET';

export const TEMPLATE_LIST_REQUEST = 'TEMPLATE_LIST_REQUEST';
export const TEMPLATE_LIST_SUCCESS = 'TEMPLATE_LIST_SUCCESS';
export const TEMPLATE_LIST_FAIL = 'TEMPLATE_LIST_FAIL';

export const TEMPLATE_DETAILS_REQUEST = 'TEMPLATE_DETAILS_REQUEST';
export const TEMPLATE_DETAILS_SUCCESS = 'TEMPLATE_DETAILS_SUCCESS';
export const TEMPLATE_DETAILS_FAIL = 'TEMPLATE_DETAILS_FAIL';

export const TEMPLATE_CREATE_REQUEST = 'TEMPLATE_CREATE_REQUEST';
export const TEMPLATE_CREATE_SUCCESS = 'TEMPLATE_CREATE_SUCCESS';
export const TEMPLATE_CREATE_FAIL = 'TEMPLATE_CREATE_FAIL';
export const TEMPLATE_CREATE_RESET = 'TEMPLATE_CREATE_RESET';

export const TEMPLATE_UPDATE_REQUEST = 'TEMPLATE_UPDATE_REQUEST';
export const TEMPLATE_UPDATE_SUCCESS = 'TEMPLATE_UPDATE_SUCCESS';
export const TEMPLATE_UPDATE_FAIL = 'TEMPLATE_UPDATE_FAIL';
export const TEMPLATE_UPDATE_RESET = 'TEMPLATE_UPDATE_RESET';

export const TEMPLATE_DELETE_REQUEST = 'TEMPLATE_DELETE_REQUEST';
export const TEMPLATE_DELETE_SUCCESS = 'TEMPLATE_DELETE_SUCCESS';
export const TEMPLATE_DELETE_FAIL = 'TEMPLATE_DELETE_FAIL';

export const RECORD_PAYMENT_REQUEST = 'RECORD_PAYMENT_REQUEST';
export const RECORD_PAYMENT_SUCCESS = 'RECORD_PAYMENT_SUCCESS';
export const RECORD_PAYMENT_FAIL = 'RECORD_PAYMENT_FAIL';
export const RECORD_PAYMENT_RESET = 'RECORD_PAYMENT_RESET';

export const CREDIT_NOTE_CREATE_REQUEST = 'CREDIT_NOTE_CREATE_REQUEST';
export const CREDIT_NOTE_CREATE_SUCCESS = 'CREDIT_NOTE_CREATE_SUCCESS';
export const CREDIT_NOTE_CREATE_FAIL = 'CREDIT_NOTE_CREATE_FAIL';
export const CREDIT_NOTE_CREATE_RESET = 'CREDIT_NOTE_CREATE_RESET';

export const DEBIT_NOTE_CREATE_REQUEST = 'DEBIT_NOTE_CREATE_REQUEST';
export const DEBIT_NOTE_CREATE_SUCCESS = 'DEBIT_NOTE_CREATE_SUCCESS';
export const DEBIT_NOTE_CREATE_FAIL = 'DEBIT_NOTE_CREATE_FAIL';
export const DEBIT_NOTE_CREATE_RESET = 'DEBIT_NOTE_CREATE_RESET';

export const BILLING_REPORT_REQUEST = 'BILLING_REPORT_REQUEST';
export const BILLING_REPORT_SUCCESS = 'BILLING_REPORT_SUCCESS';
export const BILLING_REPORT_FAIL = 'BILLING_REPORT_FAIL';

export const BILLING_CONFIG_REQUEST = 'BILLING_CONFIG_REQUEST';
export const BILLING_CONFIG_SUCCESS = 'BILLING_CONFIG_SUCCESS';
export const BILLING_CONFIG_FAIL = 'BILLING_CONFIG_FAIL';

export const BILLING_CONFIG_UPDATE_REQUEST = 'BILLING_CONFIG_UPDATE_REQUEST';
export const BILLING_CONFIG_UPDATE_SUCCESS = 'BILLING_CONFIG_UPDATE_SUCCESS';
export const BILLING_CONFIG_UPDATE_FAIL = 'BILLING_CONFIG_UPDATE_FAIL';
export const BILLING_CONFIG_UPDATE_RESET = 'BILLING_CONFIG_UPDATE_RESET';
