export const CART_ADD_ITEM = 'CARD_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CARD_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const CART_GET_FROM_DATABASE = 'CART_GET_FROM_DATABASE';
export const CART_ITEM_FAIL = 'CART_ITEM_FAIL';
export const CART_REMOVE_ITEM_FROM_DATABASE = 'CART_REMOVE_ITEM_FROM_DATABASE';
//export const CART_ITEM_DETAILS_CORRECT = 'CART_ITEM_DETAILS_CORRECT';
// export const CART_ADD_ITEM_TO_DATABSE = 'CART_ADD_ITEM_TO_DATABSE';
