export const CLASS_LIST_REQUEST = 'CLASS_LIST_REQUEST';
export const CLASS_LIST_SUCCESS = 'CLASS_LIST_SUCCESS';
export const CLASS_LIST_FAIL = 'CLASS_LIST_FAIL';

export const CLASS_CREATE_REQUEST = 'CLASS_CREATE_REQUEST';
export const CLASS_CREATE_SUCCESS = 'CLASS_CREATE_SUCCESS';
export const CLASS_CREATE_FAIL = 'CLASS_CREATE_FAIL';
export const CLASS_CREATE_RESET = 'CLASS_CREATE_RESET';

export const CLASS_UPDATE_REQUEST = 'CLASS_UPDATE_REQUEST';
export const CLASS_UPDATE_SUCCESS = 'CLASS_UPDATE_SUCCESS';
export const CLASS_UPDATE_FAIL = 'CLASS_UPDATE_FAIL';
export const CLASS_UPDATE_RESET = 'CLASS_UPDATE_RESET';

export const CLASS_DELETE_REQUEST = 'CLASS_DELETE_REQUEST';
export const CLASS_DELETE_SUCCESS = 'CLASS_DELETE_SUCCESS';
export const CLASS_DELETE_FAIL = 'CLASS_DELETE_FAIL';
