export const CAROUSEL_IMAGES_REQUEST = 'CAROUSEL_IMAGES_REQUEST';
export const CAROUSEL_IMAGES_SUCCESS = 'CAROUSEL_IMAGES_SUCCESS';
export const CAROUSEL_IMAGES_FAIL = 'CAROUSEL_IMAGES_FAIL';

export const CAROUSEL_IMAGES_UPDATE_REQUEST = 'CAROUSEL_IMAGES_UPDATE_REQUEST';
export const CAROUSEL_IMAGES_UPDATE_SUCCESS = 'CAROUSEL_IMAGES_UPDATE_SUCCESS';
export const CAROUSEL_IMAGES_UPDATE_FAIL = 'CAROUSEL_IMAGES_UPDATE_FAIL';
export const CAROUSEL_IMAGES_UPDATE_RESET = 'CAROUSEL_IMAGES_UPDATE_RESET';

export const CAROUSEL_IMAGES_DELETE_REQUEST = 'CAROUSEL_IMAGES_DELETE_REQUEST';
export const CAROUSEL_IMAGES_DELETE_SUCCESS = 'CAROUSEL_IMAGES_DELETE_SUCCESS';
export const CAROUSEL_IMAGES_DELETE_FAIL = 'CAROUSEL_IMAGES_DELETE_FAIL';

export const CAROUSEL_IMAGES_ADD_REQUEST = 'CAROUSEL_IMAGES_ADD_REQUEST';
export const CAROUSEL_IMAGES_ADD_SUCCESS = 'CAROUSEL_IMAGES_ADD_SUCCESS';
export const CAROUSEL_IMAGES_ADD_FAIL = 'CAROUSEL_IMAGES_ADD_FAIL';
export const CAROUSEL_IMAGES_ADD_RESET = 'CAROUSEL_IMAGES_ADD_RESET';

export const STATISTICS_DETAILS_REQUEST = 'STATISTICS_DETAILS_REQUEST';
export const STATISTICS_DETAILS_SUCCESS = 'STATISTICS_DETAILS_SUCCESS';
export const STATISTICS_DETAILS_FAIL = 'STATISTICS_DETAILS_FAIL';

export const STATISTICS_UPDATE_REQUEST = 'STATISTICS_UPDATE_REQUEST';
export const STATISTICS_UPDATE_SUCCESS = 'STATISTICS_UPDATE_SUCCESS';
export const STATISTICS_UPDATE_FAIL = 'STATISTICS_UPDATE_FAIL';
export const STATISTICS_UPDATE_RESET = 'STATISTICS_UPDATE_RESET';

export const HEADER_BG_DETAILS_REQUEST = 'HEADER_BG_DETAILS_REQUEST';
export const HEADER_BG_DETAILS_SUCCESS = 'HEADER_BG_DETAILS_SUCCESS';
export const HEADER_BG_DETAILS_FAIL = 'HEADER_BG_DETAILS_FAIL';

export const HEADER_BG_UPDATE_REQUEST = 'HEADER_BG_UPDATE_REQUEST';
export const HEADER_BG_UPDATE_SUCCESS = 'HEADER_BG_UPDATE_SUCCESS';
export const HEADER_BG_UPDATE_FAIL = 'HEADER_BG_UPDATE_FAIL';
export const HEADER_BG_UPDATE_RESET = 'HEADER_BG_UPDATE_RESET';

export const ANNOUNCEMENT_LIST_REQUEST = 'ANNOUNCEMENT_LIST_REQUEST';
export const ANNOUNCEMENT_LIST_SUCCESS = 'ANNOUNCEMENT_LIST_SUCCESS';
export const ANNOUNCEMENT_LIST_FAIL = 'ANNOUNCEMENT_LIST_FAIL';

export const ANNOUNCEMENT_UPDATE_REQUEST = 'ANNOUNCEMENT_UPDATE_REQUEST';
export const ANNOUNCEMENT_UPDATE_SUCCESS = 'ANNOUNCEMENT_UPDATE_SUCCESS';
export const ANNOUNCEMENT_UPDATE_FAIL = 'ANNOUNCEMENT_UPDATE_FAIL';
export const ANNOUNCEMENT_UPDATE_RESET = 'ANNOUNCEMENT_UPDATE_RESET';

export const ANNOUNCEMENT_DELETE_REQUEST = 'ANNOUNCEMENT_DELETE_REQUEST';
export const ANNOUNCEMENT_DELETE_SUCCESS = 'ANNOUNCEMENT_DELETE_SUCCESS';
export const ANNOUNCEMENT_DELETE_FAIL = 'ANNOUNCEMENT_DELETE_FAIL';

export const ANNOUNCEMENT_ADD_REQUEST = 'ANNOUNCEMENT_ADD_REQUEST';
export const ANNOUNCEMENT_ADD_SUCCESS = 'ANNOUNCEMENT_ADD_SUCCESS';
export const ANNOUNCEMENT_ADD_FAIL = 'ANNOUNCEMENT_ADD_FAIL';
export const ANNOUNCEMENT_ADD_RESET = 'ANNOUNCEMENT_ADD_RESET';
