export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_DETAILS_RESET = 'PRODUCT_DETAILS_RESET';

export const PRODUCT_NEW_SIZE_ADD_REQUEST = 'PRODUCT_NEW_SIZE_ADD_REQUEST';
export const PRODUCT_NEW_SIZE_ADD_SUCCESS = 'PRODUCT_NEW_SIZE_ADD_SUCCESS';
export const PRODUCT_NEW_SIZE_ADD_FAIL = 'PRODUCT_NEW_SIZE_ADD_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

export const PRODUCT_IMAGE_LIST_REQUEST = 'PRODUCT_IMAGE_LIST_REQUEST';
export const PRODUCT_IMAGE_LIST_SUCCESS = 'PRODUCT_IMAGE_LIST_SUCCESS';
export const PRODUCT_IMAGE_LIST_FAIL = 'PRODUCT_IMAGE_LIST_FAIL';

export const PRODUCT_IMAGE_UPLOAD_REQUEST = 'PRODUCT_IMAGE_UPLOAD_REQUEST';
export const PRODUCT_IMAGE_UPLOAD_PROGRESS = 'PRODUCT_IMAGE_UPLOAD_PROGRESS';
export const PRODUCT_IMAGE_UPLOAD_SUCCESS = 'PRODUCT_IMAGE_UPLOAD_SUCCESS';
export const PRODUCT_IMAGE_UPLOAD_FAIL = 'PRODUCT_IMAGE_UPLOAD_FAIL';
export const PRODUCT_IMAGE_UPLOAD_RESET = 'PRODUCT_IMAGE_UPLOAD_RESET';

export const PRODUCT_DISPLAY_ORDERS_REQUEST = 'PRODUCT_DISPLAY_ORDERS_REQUEST';
export const PRODUCT_DISPLAY_ORDERS_SUCCESS = 'PRODUCT_DISPLAY_ORDERS_SUCCESS';
export const PRODUCT_DISPLAY_ORDERS_FAIL = 'PRODUCT_DISPLAY_ORDERS_FAIL';

export const PRODUCT_UPDATE_FEATURED_REQUEST = 'PRODUCT_UPDATE_FEATURED_REQUEST';
export const PRODUCT_UPDATE_FEATURED_SUCCESS = 'PRODUCT_UPDATE_FEATURED_SUCCESS';
export const PRODUCT_UPDATE_FEATURED_FAIL = 'PRODUCT_UPDATE_FEATURED_FAIL';
export const PRODUCT_UPDATE_FEATURED_RESET = 'PRODUCT_UPDATE_FEATURED_RESET';
