export const RETURN_LIST_REQUEST = 'RETURN_LIST_REQUEST';
export const RETURN_LIST_SUCCESS = 'RETURN_LIST_SUCCESS';
export const RETURN_LIST_FAIL = 'RETURN_LIST_FAIL';
export const RETURN_LIST_RESET = 'RETURN_LIST_RESET';

export const RETURN_DETAILS_REQUEST = 'RETURN_DETAILS_REQUEST';
export const RETURN_DETAILS_SUCCESS = 'RETURN_DETAILS_SUCCESS';
export const RETURN_DETAILS_FAIL = 'RETURN_DETAILS_FAIL';
export const RETURN_DETAILS_RESET = 'RETURN_DETAILS_RESET';

export const RETURN_CREATE_REQUEST = 'RETURN_CREATE_REQUEST';
export const RETURN_CREATE_SUCCESS = 'RETURN_CREATE_SUCCESS';
export const RETURN_CREATE_FAIL = 'RETURN_CREATE_FAIL';
export const RETURN_CREATE_RESET = 'RETURN_CREATE_RESET';

export const RETURN_UPDATE_STATUS_REQUEST = 'RETURN_UPDATE_STATUS_REQUEST';
export const RETURN_UPDATE_STATUS_SUCCESS = 'RETURN_UPDATE_STATUS_SUCCESS';
export const RETURN_UPDATE_STATUS_FAIL = 'RETURN_UPDATE_STATUS_FAIL';
export const RETURN_UPDATE_STATUS_RESET = 'RETURN_UPDATE_STATUS_RESET';

export const RETURN_QC_UPDATE_REQUEST = 'RETURN_QC_UPDATE_REQUEST';
export const RETURN_QC_UPDATE_SUCCESS = 'RETURN_QC_UPDATE_SUCCESS';
export const RETURN_QC_UPDATE_FAIL = 'RETURN_QC_UPDATE_FAIL';
export const RETURN_QC_UPDATE_RESET = 'RETURN_QC_UPDATE_RESET';

export const RETURN_CREDIT_NOTE_REQUEST = 'RETURN_CREDIT_NOTE_REQUEST';
export const RETURN_CREDIT_NOTE_SUCCESS = 'RETURN_CREDIT_NOTE_SUCCESS';
export const RETURN_CREDIT_NOTE_FAIL = 'RETURN_CREDIT_NOTE_FAIL';
export const RETURN_CREDIT_NOTE_RESET = 'RETURN_CREDIT_NOTE_RESET';

export const RETURN_EXCHANGE_ORDER_REQUEST = 'RETURN_EXCHANGE_ORDER_REQUEST';
export const RETURN_EXCHANGE_ORDER_SUCCESS = 'RETURN_EXCHANGE_ORDER_SUCCESS';
export const RETURN_EXCHANGE_ORDER_FAIL = 'RETURN_EXCHANGE_ORDER_FAIL';
export const RETURN_EXCHANGE_ORDER_RESET = 'RETURN_EXCHANGE_ORDER_RESET';

export const RETURN_REFUND_REQUEST = 'RETURN_REFUND_REQUEST';
export const RETURN_REFUND_SUCCESS = 'RETURN_REFUND_SUCCESS';
export const RETURN_REFUND_FAIL = 'RETURN_REFUND_FAIL';
export const RETURN_REFUND_RESET = 'RETURN_REFUND_RESET';

export const RETURN_DASHBOARD_REQUEST = 'RETURN_DASHBOARD_REQUEST';
export const RETURN_DASHBOARD_SUCCESS = 'RETURN_DASHBOARD_SUCCESS';
export const RETURN_DASHBOARD_FAIL = 'RETURN_DASHBOARD_FAIL';

export const RETURN_BY_ORDER_REQUEST = 'RETURN_BY_ORDER_REQUEST';
export const RETURN_BY_ORDER_SUCCESS = 'RETURN_BY_ORDER_SUCCESS';
export const RETURN_BY_ORDER_FAIL = 'RETURN_BY_ORDER_FAIL';
export const RETURN_BY_ORDER_RESET = 'RETURN_BY_ORDER_RESET';

export const RETURN_NOTE_REQUEST = 'RETURN_NOTE_REQUEST';
export const RETURN_NOTE_SUCCESS = 'RETURN_NOTE_SUCCESS';
export const RETURN_NOTE_FAIL = 'RETURN_NOTE_FAIL';
export const RETURN_NOTE_RESET = 'RETURN_NOTE_RESET';
