export const SHIPPING_DASHBOARD_REQUEST = 'SHIPPING_DASHBOARD_REQUEST';
export const SHIPPING_DASHBOARD_SUCCESS = 'SHIPPING_DASHBOARD_SUCCESS';
export const SHIPPING_DASHBOARD_FAIL = 'SHIPPING_DASHBOARD_FAIL';

export const SHIPPING_SERVICEABILITY_REQUEST = 'SHIPPING_SERVICEABILITY_REQUEST';
export const SHIPPING_SERVICEABILITY_SUCCESS = 'SHIPPING_SERVICEABILITY_SUCCESS';
export const SHIPPING_SERVICEABILITY_FAIL = 'SHIPPING_SERVICEABILITY_FAIL';
export const SHIPPING_SERVICEABILITY_RESET = 'SHIPPING_SERVICEABILITY_RESET';

export const SHIPPING_CREATE_ORDER_REQUEST = 'SHIPPING_CREATE_ORDER_REQUEST';
export const SHIPPING_CREATE_ORDER_SUCCESS = 'SHIPPING_CREATE_ORDER_SUCCESS';
export const SHIPPING_CREATE_ORDER_FAIL = 'SHIPPING_CREATE_ORDER_FAIL';
export const SHIPPING_CREATE_ORDER_RESET = 'SHIPPING_CREATE_ORDER_RESET';

export const SHIPPING_ASSIGN_COURIER_REQUEST = 'SHIPPING_ASSIGN_COURIER_REQUEST';
export const SHIPPING_ASSIGN_COURIER_SUCCESS = 'SHIPPING_ASSIGN_COURIER_SUCCESS';
export const SHIPPING_ASSIGN_COURIER_FAIL = 'SHIPPING_ASSIGN_COURIER_FAIL';
export const SHIPPING_ASSIGN_COURIER_RESET = 'SHIPPING_ASSIGN_COURIER_RESET';

export const SHIPPING_SCHEDULE_PICKUP_REQUEST = 'SHIPPING_SCHEDULE_PICKUP_REQUEST';
export const SHIPPING_SCHEDULE_PICKUP_SUCCESS = 'SHIPPING_SCHEDULE_PICKUP_SUCCESS';
export const SHIPPING_SCHEDULE_PICKUP_FAIL = 'SHIPPING_SCHEDULE_PICKUP_FAIL';
export const SHIPPING_SCHEDULE_PICKUP_RESET = 'SHIPPING_SCHEDULE_PICKUP_RESET';

export const SHIPPING_GENERATE_LABEL_REQUEST = 'SHIPPING_GENERATE_LABEL_REQUEST';
export const SHIPPING_GENERATE_LABEL_SUCCESS = 'SHIPPING_GENERATE_LABEL_SUCCESS';
export const SHIPPING_GENERATE_LABEL_FAIL = 'SHIPPING_GENERATE_LABEL_FAIL';

export const SHIPPING_GENERATE_MANIFEST_REQUEST = 'SHIPPING_GENERATE_MANIFEST_REQUEST';
export const SHIPPING_GENERATE_MANIFEST_SUCCESS = 'SHIPPING_GENERATE_MANIFEST_SUCCESS';
export const SHIPPING_GENERATE_MANIFEST_FAIL = 'SHIPPING_GENERATE_MANIFEST_FAIL';

export const SHIPPING_TRACK_ORDER_REQUEST = 'SHIPPING_TRACK_ORDER_REQUEST';
export const SHIPPING_TRACK_ORDER_SUCCESS = 'SHIPPING_TRACK_ORDER_SUCCESS';
export const SHIPPING_TRACK_ORDER_FAIL = 'SHIPPING_TRACK_ORDER_FAIL';

export const SHIPPING_NDR_LIST_REQUEST = 'SHIPPING_NDR_LIST_REQUEST';
export const SHIPPING_NDR_LIST_SUCCESS = 'SHIPPING_NDR_LIST_SUCCESS';
export const SHIPPING_NDR_LIST_FAIL = 'SHIPPING_NDR_LIST_FAIL';

export const SHIPPING_NDR_DETAILS_REQUEST = 'SHIPPING_NDR_DETAILS_REQUEST';
export const SHIPPING_NDR_DETAILS_SUCCESS = 'SHIPPING_NDR_DETAILS_SUCCESS';
export const SHIPPING_NDR_DETAILS_FAIL = 'SHIPPING_NDR_DETAILS_FAIL';

export const SHIPPING_NDR_REATTEMPT_REQUEST = 'SHIPPING_NDR_REATTEMPT_REQUEST';
export const SHIPPING_NDR_REATTEMPT_SUCCESS = 'SHIPPING_NDR_REATTEMPT_SUCCESS';
export const SHIPPING_NDR_REATTEMPT_FAIL = 'SHIPPING_NDR_REATTEMPT_FAIL';
export const SHIPPING_NDR_REATTEMPT_RESET = 'SHIPPING_NDR_REATTEMPT_RESET';

export const SHIPPING_NDR_RTO_REQUEST = 'SHIPPING_NDR_RTO_REQUEST';
export const SHIPPING_NDR_RTO_SUCCESS = 'SHIPPING_NDR_RTO_SUCCESS';
export const SHIPPING_NDR_RTO_FAIL = 'SHIPPING_NDR_RTO_FAIL';
export const SHIPPING_NDR_RTO_RESET = 'SHIPPING_NDR_RTO_RESET';

export const SHIPPING_CANCEL_REQUEST = 'SHIPPING_CANCEL_REQUEST';
export const SHIPPING_CANCEL_SUCCESS = 'SHIPPING_CANCEL_SUCCESS';
export const SHIPPING_CANCEL_FAIL = 'SHIPPING_CANCEL_FAIL';
export const SHIPPING_CANCEL_RESET = 'SHIPPING_CANCEL_RESET';

export const SHIPPING_PICKUP_LOCATIONS_REQUEST = 'SHIPPING_PICKUP_LOCATIONS_REQUEST';
export const SHIPPING_PICKUP_LOCATIONS_SUCCESS = 'SHIPPING_PICKUP_LOCATIONS_SUCCESS';
export const SHIPPING_PICKUP_LOCATIONS_FAIL = 'SHIPPING_PICKUP_LOCATIONS_FAIL';

export const SHIPPING_GENERATE_INVOICE_REQUEST = 'SHIPPING_GENERATE_INVOICE_REQUEST';
export const SHIPPING_GENERATE_INVOICE_SUCCESS = 'SHIPPING_GENERATE_INVOICE_SUCCESS';
export const SHIPPING_GENERATE_INVOICE_FAIL = 'SHIPPING_GENERATE_INVOICE_FAIL';

export const SHIPPING_ADD_PICKUP_REQUEST = 'SHIPPING_ADD_PICKUP_REQUEST';
export const SHIPPING_ADD_PICKUP_SUCCESS = 'SHIPPING_ADD_PICKUP_SUCCESS';
export const SHIPPING_ADD_PICKUP_FAIL = 'SHIPPING_ADD_PICKUP_FAIL';
export const SHIPPING_ADD_PICKUP_RESET = 'SHIPPING_ADD_PICKUP_RESET';
