export const STOCK_DASHBOARD_REQUEST = 'STOCK_DASHBOARD_REQUEST';
export const STOCK_DASHBOARD_SUCCESS = 'STOCK_DASHBOARD_SUCCESS';
export const STOCK_DASHBOARD_FAIL = 'STOCK_DASHBOARD_FAIL';

export const STOCK_OVERVIEW_REQUEST = 'STOCK_OVERVIEW_REQUEST';
export const STOCK_OVERVIEW_SUCCESS = 'STOCK_OVERVIEW_SUCCESS';
export const STOCK_OVERVIEW_FAIL = 'STOCK_OVERVIEW_FAIL';

export const STOCK_PRODUCT_DETAILS_REQUEST = 'STOCK_PRODUCT_DETAILS_REQUEST';
export const STOCK_PRODUCT_DETAILS_SUCCESS = 'STOCK_PRODUCT_DETAILS_SUCCESS';
export const STOCK_PRODUCT_DETAILS_FAIL = 'STOCK_PRODUCT_DETAILS_FAIL';
export const STOCK_PRODUCT_DETAILS_RESET = 'STOCK_PRODUCT_DETAILS_RESET';

export const STOCK_ADJUST_REQUEST = 'STOCK_ADJUST_REQUEST';
export const STOCK_ADJUST_SUCCESS = 'STOCK_ADJUST_SUCCESS';
export const STOCK_ADJUST_FAIL = 'STOCK_ADJUST_FAIL';
export const STOCK_ADJUST_RESET = 'STOCK_ADJUST_RESET';

export const STOCK_BULK_ADJUST_REQUEST = 'STOCK_BULK_ADJUST_REQUEST';
export const STOCK_BULK_ADJUST_SUCCESS = 'STOCK_BULK_ADJUST_SUCCESS';
export const STOCK_BULK_ADJUST_FAIL = 'STOCK_BULK_ADJUST_FAIL';
export const STOCK_BULK_ADJUST_RESET = 'STOCK_BULK_ADJUST_RESET';

export const STOCK_MOVEMENTS_REQUEST = 'STOCK_MOVEMENTS_REQUEST';
export const STOCK_MOVEMENTS_SUCCESS = 'STOCK_MOVEMENTS_SUCCESS';
export const STOCK_MOVEMENTS_FAIL = 'STOCK_MOVEMENTS_FAIL';

export const STOCK_ALERTS_REQUEST = 'STOCK_ALERTS_REQUEST';
export const STOCK_ALERTS_SUCCESS = 'STOCK_ALERTS_SUCCESS';
export const STOCK_ALERTS_FAIL = 'STOCK_ALERTS_FAIL';

export const STOCK_ALERT_ACKNOWLEDGE_REQUEST = 'STOCK_ALERT_ACKNOWLEDGE_REQUEST';
export const STOCK_ALERT_ACKNOWLEDGE_SUCCESS = 'STOCK_ALERT_ACKNOWLEDGE_SUCCESS';
export const STOCK_ALERT_ACKNOWLEDGE_FAIL = 'STOCK_ALERT_ACKNOWLEDGE_FAIL';
export const STOCK_ALERT_ACKNOWLEDGE_RESET = 'STOCK_ALERT_ACKNOWLEDGE_RESET';

export const STOCK_VALUATION_REQUEST = 'STOCK_VALUATION_REQUEST';
export const STOCK_VALUATION_SUCCESS = 'STOCK_VALUATION_SUCCESS';
export const STOCK_VALUATION_FAIL = 'STOCK_VALUATION_FAIL';

export const STOCK_VALUATION_FILTERS_REQUEST = 'STOCK_VALUATION_FILTERS_REQUEST';
export const STOCK_VALUATION_FILTERS_SUCCESS = 'STOCK_VALUATION_FILTERS_SUCCESS';
export const STOCK_VALUATION_FILTERS_FAIL = 'STOCK_VALUATION_FILTERS_FAIL';

export const STOCK_VELOCITY_REQUEST = 'STOCK_VELOCITY_REQUEST';
export const STOCK_VELOCITY_SUCCESS = 'STOCK_VELOCITY_SUCCESS';
export const STOCK_VELOCITY_FAIL = 'STOCK_VELOCITY_FAIL';
