export const TYPE_LIST_REQUEST = 'TYPE_LIST_REQUEST';
export const TYPE_LIST_SUCCESS = 'TYPE_LIST_SUCCESS';
export const TYPE_LIST_FAIL = 'TYPE_LIST_FAIL';

export const TYPE_SIZES_LIST_REQUEST = 'TYPE_SIZES_LIST_REQUEST';
export const TYPE_SIZES_LIST_SUCCESS = 'TYPE_SIZES_LIST_SUCCESS';
export const TYPE_SIZES_LIST_FAIL = 'TYPE_SIZES_LIST_FAIL';
export const TYPE_SIZES_LIST_RESET = 'TYPE_SIZES_LIST_RESET';
