export const TYPE_LIST_REQUEST = 'TYPE_LIST_REQUEST';
export const TYPE_LIST_SUCCESS = 'TYPE_LIST_SUCCESS';
export const TYPE_LIST_FAIL = 'TYPE_LIST_FAIL';

export const TYPE_SIZES_LIST_REQUEST = 'TYPE_SIZES_LIST_REQUEST';
export const TYPE_SIZES_LIST_SUCCESS = 'TYPE_SIZES_LIST_SUCCESS';
export const TYPE_SIZES_LIST_FAIL = 'TYPE_SIZES_LIST_FAIL';
export const TYPE_SIZES_LIST_RESET = 'TYPE_SIZES_LIST_RESET';

export const TYPE_LIST_ALL_REQUEST = 'TYPE_LIST_ALL_REQUEST';
export const TYPE_LIST_ALL_SUCCESS = 'TYPE_LIST_ALL_SUCCESS';
export const TYPE_LIST_ALL_FAIL = 'TYPE_LIST_ALL_FAIL';

export const TYPE_DELETE_REQUEST = 'TYPE_DELETE_REQUEST';
export const TYPE_DELETE_SUCCESS = 'TYPE_DELETE_SUCCESS';
export const TYPE_DELETE_FAIL = 'TYPE_DELETE_FAIL';

export const TYPE_CREATE_REQUEST = 'TYPE_CREATE_REQUEST';
export const TYPE_CREATE_SUCCESS = 'TYPE_CREATE_SUCCESS';
export const TYPE_CREATE_FAIL = 'TYPE_CREATE_FAIL';
export const TYPE_CREATE_RESET = 'TYPE_CREATE_RESET';

export const TYPE_UPDATE_REQUEST = 'TYPE_UPDATE_REQUEST';
export const TYPE_UPDATE_SUCCESS = 'TYPE_UPDATE_SUCCESS';
export const TYPE_UPDATE_FAIL = 'TYPE_UPDATE_FAIL';
export const TYPE_UPDATE_RESET = 'TYPE_UPDATE_RESET';

export const TYPE_DETAILS_REQUEST = 'TYPE_DETAILS_REQUEST';
export const TYPE_DETAILS_SUCCESS = 'TYPE_DETAILS_SUCCESS';
export const TYPE_DETAILS_FAIL = 'TYPE_DETAILS_FAIL';
export const TYPE_DETAILS_RESET = 'TYPE_DETAILS_RESET';
