export const PRODUCT_IMAGE_DELETE_REQUEST = 'PRODUCT_IMAGE_DELETE_REQUEST';
export const PRODUCT_IMAGE_DELETE_SUCCESS = 'PRODUCT_IMAGE_DELETE_SUCCESS';
export const PRODUCT_IMAGE_DELETE_FAIL = 'PRODUCT_IMAGE_DELETE_FAIL';

export const SCHOOL_IMAGE_DELETE_REQUEST = 'SCHOOL_IMAGE_DELETE_REQUEST';
export const SCHOOL_IMAGE_DELETE_SUCCESS = 'SCHOOL_IMAGE_DELETE_SUCCESS';
export const SCHOOL_IMAGE_DELETE_FAIL = 'SCHOOL_IMAGE_DELETE_FAIL';

export const EXTRA_IMAGE_LIST_REQUEST = 'EXTRA_IMAGE_LIST_REQUEST';
export const EXTRA_IMAGE_LIST_SUCCESS = 'EXTRA_IMAGE_LIST_SUCCESS';
export const EXTRA_IMAGE_LIST_FAIL = 'EXTRA_IMAGE_LIST_FAIL';

export const EXTRA_IMAGE_UPLOAD_REQUEST = 'EXTRA_IMAGE_UPLOAD_REQUEST';
export const EXTRA_IMAGE_UPLOAD_SUCCESS = 'EXTRA_IMAGE_UPLOAD_SUCCESS';
export const EXTRA_IMAGE_UPLOAD_FAIL = 'EXTRA_IMAGE_UPLOAD_FAIL';

export const EXTRA_IMAGE_DELETE_REQUEST = 'EXTRA_IMAGE_DELETE_REQUEST';
export const EXTRA_IMAGE_DELETE_SUCCESS = 'EXTRA_IMAGE_DELETE_SUCCESS';
export const EXTRA_IMAGE_DELETE_FAIL = 'EXTRA_IMAGE_DELETE_FAIL';
